-- Anzo Insurance 数据库初始化脚本
-- 当前版本按后端运行时真实表结构整理，可直接用于创建数据库

CREATE DATABASE IF NOT EXISTS `anzo_insurance_dev` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `anzo_insurance_dev`;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `enterprise` (
  `id` VARCHAR(36) NOT NULL COMMENT '企业ID',
  `name` VARCHAR(100) NOT NULL COMMENT '企业名称',
  `credit_code` VARCHAR(18) NOT NULL COMMENT '统一社会信用代码',
  `contact_name` VARCHAR(50) NOT NULL COMMENT '联系人姓名',
  `contact_phone` VARCHAR(20) NOT NULL COMMENT '联系人手机',
  `contact_email` VARCHAR(100) DEFAULT NULL COMMENT '联系人邮箱',
  `address` VARCHAR(500) DEFAULT NULL COMMENT '企业地址',
  `description` TEXT COMMENT '企业介绍',
  `license_url` VARCHAR(500) DEFAULT NULL COMMENT '营业执照URL',
  `status` ENUM('PENDING_REVIEW', 'ACTIVE', 'REJECTED', 'DISABLED', 'EXPIRED') NOT NULL DEFAULT 'PENDING_REVIEW',
  `balance` DECIMAL(15,2) NOT NULL DEFAULT 0.00 COMMENT '钱包余额',
  `frozen_balance` DECIMAL(15,2) NOT NULL DEFAULT 0.00 COMMENT '冻结金额',
  `total_recharged` DECIMAL(15,2) NOT NULL DEFAULT 0.00 COMMENT '累计充值',
  `total_consumed` DECIMAL(15,2) NOT NULL DEFAULT 0.00 COMMENT '累计消费',
  `review_at` DATETIME DEFAULT NULL COMMENT '审核时间',
  `review_by` VARCHAR(36) DEFAULT NULL COMMENT '审核人',
  `review_remark` TEXT COMMENT '审核备注',
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_enterprise_credit_code` (`credit_code`),
  KEY `idx_enterprise_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='企业表';

CREATE TABLE IF NOT EXISTS `user` (
  `id` VARCHAR(36) NOT NULL COMMENT '用户ID',
  `enterprise_id` VARCHAR(36) NOT NULL COMMENT '企业ID',
  `username` VARCHAR(100) NOT NULL COMMENT '用户名',
  `password_hash` VARCHAR(255) NOT NULL COMMENT '密码哈希',
  `real_name` VARCHAR(50) NOT NULL COMMENT '真实姓名',
  `phone` VARCHAR(20) NOT NULL COMMENT '手机号',
  `email` VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  `role` ENUM('SUPER_ADMIN', 'ADMIN', 'OPERATOR', 'FINANCE') NOT NULL DEFAULT 'OPERATOR',
  `status` ENUM('ACTIVE', 'DISABLED') NOT NULL DEFAULT 'ACTIVE',
  `last_login_at` DATETIME DEFAULT NULL COMMENT '最后登录时间',
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_username` (`username`),
  KEY `idx_user_enterprise_id` (`enterprise_id`),
  KEY `idx_user_role` (`role`),
  KEY `idx_user_status` (`status`),
  CONSTRAINT `fk_user_enterprise` FOREIGN KEY (`enterprise_id`) REFERENCES `enterprise` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

CREATE TABLE IF NOT EXISTS `customer` (
  `id` VARCHAR(36) NOT NULL,
  `enterprise_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL COMMENT '客户企业名称',
  `credit_code` VARCHAR(18) DEFAULT NULL COMMENT '统一社会信用代码',
  `contact_name` VARCHAR(50) NOT NULL COMMENT '联系人姓名',
  `contact_phone` VARCHAR(20) NOT NULL COMMENT '联系人手机',
  `contact_email` VARCHAR(100) DEFAULT NULL COMMENT '联系人邮箱',
  `address` VARCHAR(500) DEFAULT NULL COMMENT '地址',
  `country` VARCHAR(50) DEFAULT NULL COMMENT '国家',
  `city` VARCHAR(50) DEFAULT NULL COMMENT '城市',
  `status` ENUM('ACTIVE', 'DISABLED') NOT NULL DEFAULT 'ACTIVE',
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_customer_enterprise_id` (`enterprise_id`),
  KEY `idx_customer_name` (`name`),
  CONSTRAINT `fk_customer_enterprise` FOREIGN KEY (`enterprise_id`) REFERENCES `enterprise` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客户表';

CREATE TABLE IF NOT EXISTS `insurance_insurer` (
  `id` VARCHAR(36) NOT NULL COMMENT '保险公司ID',
  `insurer_no` VARCHAR(30) NOT NULL COMMENT '保司编号',
  `insurer_name` VARCHAR(100) NOT NULL COMMENT '保司名称',
  `insurer_name_en` VARCHAR(100) DEFAULT NULL COMMENT '保司英文名称',
  `contact_name` VARCHAR(50) DEFAULT NULL COMMENT '联系人',
  `contact_phone` VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
  `contact_email` VARCHAR(100) DEFAULT NULL COMMENT '联系邮箱',
  `address` VARCHAR(255) DEFAULT NULL COMMENT '联系地址',
  `status` ENUM('ACTIVE', 'DISABLED') NOT NULL DEFAULT 'ACTIVE',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_insurance_insurer_no` (`insurer_no`),
  UNIQUE KEY `uk_insurance_insurer_name` (`insurer_name`),
  KEY `idx_insurance_insurer_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='保险公司表';

CREATE TABLE IF NOT EXISTS `insurance_application` (
  `id` VARCHAR(36) NOT NULL,
  `enterprise_id` VARCHAR(36) NOT NULL,
  `application_no` VARCHAR(50) NOT NULL COMMENT '投保申请单号',
  `trade_direction` ENUM('IMPORT', 'EXPORT', 'DOMESTIC') DEFAULT NULL,
  `transport_type` ENUM('SEA', 'AIR', 'RAIL', 'ROAD', 'MULTIMODAL') DEFAULT NULL,
  `insurance_product` ENUM('CARGO', 'LIABILITY') DEFAULT NULL,
  `insurer_id` VARCHAR(36) DEFAULT NULL,
  `insurer_name` VARCHAR(100) DEFAULT NULL,
  `applicant_id` VARCHAR(36) DEFAULT NULL,
  `insured_id` VARCHAR(36) DEFAULT NULL,
  `departure_country` VARCHAR(50) DEFAULT NULL,
  `departure_city` VARCHAR(50) DEFAULT NULL,
  `arrival_country` VARCHAR(50) DEFAULT NULL,
  `arrival_city` VARCHAR(50) DEFAULT NULL,
  `departure_date` DATE DEFAULT NULL,
  `arrival_date` DATE DEFAULT NULL,
  `transport_details` JSON DEFAULT NULL,
  `cargo_name` VARCHAR(200) DEFAULT NULL,
  `cargo_category` VARCHAR(50) DEFAULT NULL,
  `packing_type` VARCHAR(50) DEFAULT NULL,
  `packing_quantity` INT DEFAULT NULL,
  `shipping_mark` VARCHAR(500) DEFAULT NULL,
  `currency` VARCHAR(10) NOT NULL DEFAULT 'CNY',
  `insurance_amount` DECIMAL(15,2) DEFAULT NULL,
  `invoice_amount` DECIMAL(15,2) DEFAULT NULL,
  `addition_ratio` DECIMAL(5,2) DEFAULT 1.10,
  `deductible` DECIMAL(15,2) DEFAULT NULL,
  `special_terms` TEXT,
  `premium` DECIMAL(15,2) DEFAULT NULL,
  `premium_currency` VARCHAR(10) NOT NULL DEFAULT 'CNY',
  `rate` DECIMAL(10,6) DEFAULT NULL,
  `status` ENUM('DRAFT', 'SUBMITTED', 'UNDERWRITING', 'UNDERWRITTEN', 'ACTIVE', 'EXPIRED', 'CANCELLED', 'MODIFYING') NOT NULL DEFAULT 'DRAFT',
  `reject_reason` TEXT,
  `submitted_at` DATETIME DEFAULT NULL,
  `underwriting_at` DATETIME DEFAULT NULL,
  `effective_at` DATETIME DEFAULT NULL,
  `expired_at` DATETIME DEFAULT NULL,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_insurance_application_no` (`application_no`),
  KEY `idx_insurance_application_enterprise_id` (`enterprise_id`),
  KEY `idx_insurance_application_status` (`status`),
  CONSTRAINT `fk_insurance_application_enterprise` FOREIGN KEY (`enterprise_id`) REFERENCES `enterprise` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_insurance_application_applicant` FOREIGN KEY (`applicant_id`) REFERENCES `customer` (`id`),
  CONSTRAINT `fk_insurance_application_insured` FOREIGN KEY (`insured_id`) REFERENCES `customer` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='投保申请表，草稿和正式申请共用';

CREATE TABLE IF NOT EXISTS `application_template` (
  `id` VARCHAR(36) NOT NULL,
  `enterprise_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `trade_direction` ENUM('IMPORT', 'EXPORT', 'DOMESTIC') NOT NULL,
  `transport_type` ENUM('SEA', 'AIR', 'RAIL', 'ROAD', 'MULTIMODAL') NOT NULL,
  `insurance_product` ENUM('CARGO', 'LIABILITY') NOT NULL DEFAULT 'CARGO',
  `insurer_id` VARCHAR(36) DEFAULT NULL,
  `applicant_id` VARCHAR(36) DEFAULT NULL,
  `insured_id` VARCHAR(36) DEFAULT NULL,
  `departure_country` VARCHAR(50) DEFAULT NULL,
  `departure_city` VARCHAR(50) DEFAULT NULL,
  `arrival_country` VARCHAR(50) DEFAULT NULL,
  `arrival_city` VARCHAR(50) DEFAULT NULL,
  `cargo_category` VARCHAR(50) DEFAULT NULL,
  `packing_type` VARCHAR(50) DEFAULT NULL,
  `addition_ratio` DECIMAL(5,2) NOT NULL DEFAULT 1.10,
  `special_terms` TEXT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_application_template_enterprise_id` (`enterprise_id`),
  CONSTRAINT `fk_application_template_enterprise` FOREIGN KEY (`enterprise_id`) REFERENCES `enterprise` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='投保模板表';

CREATE TABLE IF NOT EXISTS `t_policy` (
  `id` VARCHAR(36) NOT NULL,
  `policy_no` VARCHAR(64) NOT NULL,
  `application_id` VARCHAR(36) NOT NULL,
  `enterprise_id` VARCHAR(36) NOT NULL,
  `applicant_user_id` VARCHAR(36) DEFAULT NULL,
  `status` INT NOT NULL DEFAULT 0 COMMENT '0-已提交,1-待审核,2-保司审核中,3-已承保,4-已生效,5-已撤销,6-已退保,7-已过期',
  `insurer_id` VARCHAR(36) DEFAULT NULL,
  `insurer_name` VARCHAR(100) DEFAULT NULL,
  `trade_direction` INT DEFAULT NULL,
  `transport_mode` INT DEFAULT NULL,
  `applicant_name` VARCHAR(100) DEFAULT NULL,
  `insured_name` VARCHAR(100) DEFAULT NULL,
  `cargo_name` VARCHAR(200) DEFAULT NULL,
  `cargo_category` VARCHAR(100) DEFAULT NULL,
  `packing_method` VARCHAR(100) DEFAULT NULL,
  `packing_quantity` INT DEFAULT NULL,
  `shipping_mark` VARCHAR(500) DEFAULT NULL,
  `insured_amount` DECIMAL(15,2) DEFAULT NULL,
  `currency` VARCHAR(10) NOT NULL DEFAULT 'CNY',
  `invoice_amount` DECIMAL(15,2) DEFAULT NULL,
  `addition_rate` DECIMAL(10,4) DEFAULT NULL,
  `deductible_amount` DECIMAL(15,2) DEFAULT NULL,
  `premium_amount` DECIMAL(15,2) DEFAULT NULL,
  `rate` DECIMAL(10,6) DEFAULT NULL,
  `rate_display` VARCHAR(50) DEFAULT NULL,
  `rate_calculation_desc` VARCHAR(500) DEFAULT NULL,
  `origin_country` VARCHAR(50) DEFAULT NULL,
  `origin_city` VARCHAR(50) DEFAULT NULL,
  `destination_country` VARCHAR(50) DEFAULT NULL,
  `destination_city` VARCHAR(50) DEFAULT NULL,
  `departure_date` DATE DEFAULT NULL,
  `expected_arrival_date` DATE DEFAULT NULL,
  `transport_vehicle_info` VARCHAR(255) DEFAULT NULL,
  `document_no` VARCHAR(100) DEFAULT NULL,
  `special_agreements` TEXT,
  `remark` VARCHAR(500) DEFAULT NULL,
  `effective_date` DATE DEFAULT NULL,
  `expiry_date` DATE DEFAULT NULL,
  `policy_file_url` VARCHAR(500) DEFAULT NULL,
  `policy_file_name` VARCHAR(255) DEFAULT NULL,
  `policy_file_size` BIGINT DEFAULT NULL,
  `cancellation_reason` VARCHAR(500) DEFAULT NULL,
  `cancellation_time` DATETIME DEFAULT NULL,
  `surrender_reason` VARCHAR(500) DEFAULT NULL,
  `surrender_time` DATETIME DEFAULT NULL,
  `refund_amount` DECIMAL(15,2) DEFAULT NULL,
  `insurer_policy_no` VARCHAR(100) DEFAULT NULL,
  `insurer_confirmed_time` DATETIME DEFAULT NULL,
  `application_date` DATE DEFAULT NULL,
  `submission_time` DATETIME DEFAULT NULL,
  `create_user_name` VARCHAR(100) DEFAULT NULL,
  `update_user_name` VARCHAR(100) DEFAULT NULL,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_t_policy_no` (`policy_no`),
  KEY `idx_t_policy_enterprise_id` (`enterprise_id`),
  KEY `idx_t_policy_status` (`status`),
  CONSTRAINT `fk_t_policy_enterprise` FOREIGN KEY (`enterprise_id`) REFERENCES `enterprise` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_t_policy_application` FOREIGN KEY (`application_id`) REFERENCES `insurance_application` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='保单表';

CREATE TABLE IF NOT EXISTS `t_claim` (
  `id` VARCHAR(36) NOT NULL,
  `claim_no` VARCHAR(64) NOT NULL,
  `enterprise_id` VARCHAR(36) NOT NULL,
  `policy_id` VARCHAR(36) NOT NULL,
  `policy_no` VARCHAR(64) DEFAULT NULL,
  `insured_name` VARCHAR(100) DEFAULT NULL,
  `insured_contact_name` VARCHAR(100) DEFAULT NULL,
  `insured_contact_phone` VARCHAR(30) DEFAULT NULL,
  `report_date` DATE DEFAULT NULL,
  `accident_date` DATE DEFAULT NULL,
  `accident_location` VARCHAR(255) DEFAULT NULL,
  `accident_description` TEXT,
  `accident_type` VARCHAR(50) DEFAULT NULL,
  `accident_type_other` VARCHAR(255) DEFAULT NULL,
  `claim_amount` DECIMAL(15,2) DEFAULT NULL,
  `currency` VARCHAR(10) NOT NULL DEFAULT 'CNY',
  `loss_description` TEXT,
  `loss_reason` TEXT,
  `material_status` VARCHAR(50) DEFAULT NULL,
  `missing_materials` TEXT,
  `status` VARCHAR(50) NOT NULL DEFAULT 'REPORTED',
  `handler_user_id` VARCHAR(36) DEFAULT NULL,
  `handler_user_name` VARCHAR(100) DEFAULT NULL,
  `handler_assigned_at` DATETIME DEFAULT NULL,
  `review_user_id` VARCHAR(36) DEFAULT NULL,
  `review_user_name` VARCHAR(100) DEFAULT NULL,
  `review_at` DATETIME DEFAULT NULL,
  `review_remark` VARCHAR(500) DEFAULT NULL,
  `survey_user_id` VARCHAR(36) DEFAULT NULL,
  `survey_user_name` VARCHAR(100) DEFAULT NULL,
  `survey_at` DATETIME DEFAULT NULL,
  `survey_report` TEXT,
  `payment_user_id` VARCHAR(36) DEFAULT NULL,
  `payment_user_name` VARCHAR(100) DEFAULT NULL,
  `payment_at` DATETIME DEFAULT NULL,
  `payment_amount` DECIMAL(15,2) DEFAULT NULL,
  `payment_currency` VARCHAR(10) DEFAULT NULL,
  `reject_reason` VARCHAR(500) DEFAULT NULL,
  `withdraw_reason` VARCHAR(500) DEFAULT NULL,
  `status_changed_at` DATETIME DEFAULT NULL,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_t_claim_no` (`claim_no`),
  KEY `idx_t_claim_enterprise_id` (`enterprise_id`),
  KEY `idx_t_claim_status` (`status`),
  CONSTRAINT `fk_t_claim_enterprise` FOREIGN KEY (`enterprise_id`) REFERENCES `enterprise` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_t_claim_policy` FOREIGN KEY (`policy_id`) REFERENCES `t_policy` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='理赔表';

CREATE TABLE IF NOT EXISTS `t_claim_material` (
  `id` VARCHAR(36) NOT NULL,
  `claim_id` VARCHAR(36) NOT NULL,
  `material_type` VARCHAR(50) NOT NULL,
  `material_name` VARCHAR(200) NOT NULL,
  `material_description` VARCHAR(500) DEFAULT NULL,
  `file_url` VARCHAR(500) DEFAULT NULL,
  `file_name` VARCHAR(255) DEFAULT NULL,
  `file_size` BIGINT DEFAULT NULL,
  `file_type` VARCHAR(100) DEFAULT NULL,
  `upload_user_id` VARCHAR(36) DEFAULT NULL,
  `upload_user_name` VARCHAR(100) DEFAULT NULL,
  `upload_time` DATETIME DEFAULT NULL,
  `is_required` TINYINT(1) NOT NULL DEFAULT 0,
  `is_approved` TINYINT(1) NOT NULL DEFAULT 0,
  `approve_user_id` VARCHAR(36) DEFAULT NULL,
  `approve_user_name` VARCHAR(100) DEFAULT NULL,
  `approve_time` DATETIME DEFAULT NULL,
  `approve_remark` VARCHAR(500) DEFAULT NULL,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_t_claim_material_claim_id` (`claim_id`),
  CONSTRAINT `fk_t_claim_material_claim` FOREIGN KEY (`claim_id`) REFERENCES `t_claim` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='理赔材料表';

CREATE TABLE IF NOT EXISTS `t_claim_process_record` (
  `id` VARCHAR(36) NOT NULL,
  `claim_id` VARCHAR(36) NOT NULL,
  `from_status` VARCHAR(50) DEFAULT NULL,
  `to_status` VARCHAR(50) DEFAULT NULL,
  `process_type` VARCHAR(50) DEFAULT NULL,
  `process_content` VARCHAR(500) DEFAULT NULL,
  `attachment_url` VARCHAR(500) DEFAULT NULL,
  `attachment_name` VARCHAR(255) DEFAULT NULL,
  `operator_user_id` VARCHAR(36) DEFAULT NULL,
  `operator_user_name` VARCHAR(100) DEFAULT NULL,
  `operation_time` DATETIME DEFAULT NULL,
  `is_internal` TINYINT(1) NOT NULL DEFAULT 0,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_t_claim_process_record_claim_id` (`claim_id`),
  CONSTRAINT `fk_t_claim_process_record_claim` FOREIGN KEY (`claim_id`) REFERENCES `t_claim` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='理赔处理记录表';

CREATE TABLE IF NOT EXISTS `t_wallet` (
  `id` VARCHAR(36) NOT NULL,
  `enterprise_id` VARCHAR(36) NOT NULL,
  `available_balance` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `frozen_balance` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `total_recharge_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `total_consumption_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `total_refund_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `currency` VARCHAR(10) NOT NULL DEFAULT 'CNY',
  `min_balance_alert` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `balance_alert_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `status` INT NOT NULL DEFAULT 0,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_t_wallet_enterprise_id` (`enterprise_id`),
  CONSTRAINT `fk_t_wallet_enterprise` FOREIGN KEY (`enterprise_id`) REFERENCES `enterprise` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='企业钱包表';

CREATE TABLE IF NOT EXISTS `t_transaction_record` (
  `id` VARCHAR(36) NOT NULL,
  `transaction_no` VARCHAR(64) NOT NULL,
  `enterprise_id` VARCHAR(36) NOT NULL,
  `transaction_type` INT NOT NULL,
  `amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `currency` VARCHAR(10) NOT NULL DEFAULT 'CNY',
  `balance_before` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `balance_after` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `frozen_before` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `frozen_after` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `related_business_id` VARCHAR(36) DEFAULT NULL,
  `related_business_type` VARCHAR(32) DEFAULT NULL,
  `related_business_desc` VARCHAR(255) DEFAULT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `transaction_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_time` DATETIME DEFAULT NULL,
  `payment_method` VARCHAR(32) DEFAULT NULL,
  `payment_no` VARCHAR(100) DEFAULT NULL,
  `remark` VARCHAR(500) DEFAULT NULL,
  `operator_user_id` VARCHAR(36) DEFAULT NULL,
  `operator_user_name` VARCHAR(100) DEFAULT NULL,
  `is_manual` TINYINT(1) NOT NULL DEFAULT 0,
  `audit_status` INT NOT NULL DEFAULT 0,
  `audit_opinion` VARCHAR(500) DEFAULT NULL,
  `audit_time` DATETIME DEFAULT NULL,
  `auditor_user_id` VARCHAR(36) DEFAULT NULL,
  `auditor_user_name` VARCHAR(100) DEFAULT NULL,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_t_transaction_record_no` (`transaction_no`),
  KEY `idx_t_transaction_record_enterprise_id` (`enterprise_id`),
  CONSTRAINT `fk_t_transaction_record_enterprise` FOREIGN KEY (`enterprise_id`) REFERENCES `enterprise` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='交易流水表';

CREATE TABLE IF NOT EXISTS `t_bill` (
  `id` VARCHAR(36) NOT NULL,
  `bill_no` VARCHAR(64) NOT NULL,
  `enterprise_id` VARCHAR(36) NOT NULL,
  `bill_type` INT NOT NULL DEFAULT 1,
  `period_start_date` DATE DEFAULT NULL,
  `period_end_date` DATE DEFAULT NULL,
  `generation_date` DATE DEFAULT NULL,
  `total_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `paid_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `deduction_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `receivable_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `currency` VARCHAR(10) NOT NULL DEFAULT 'CNY',
  `status` INT NOT NULL DEFAULT 0,
  `sent_time` DATETIME DEFAULT NULL,
  `confirmed_time` DATETIME DEFAULT NULL,
  `paid_time` DATETIME DEFAULT NULL,
  `payment_method` VARCHAR(32) DEFAULT NULL,
  `payment_no` VARCHAR(100) DEFAULT NULL,
  `overdue_days` INT DEFAULT 0,
  `overdue_fee` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `due_date` DATE DEFAULT NULL,
  `remark` VARCHAR(500) DEFAULT NULL,
  `bill_details` TEXT,
  `reconciliation_status` INT NOT NULL DEFAULT 0,
  `reconciliation_time` DATETIME DEFAULT NULL,
  `reconciliation_user_id` VARCHAR(36) DEFAULT NULL,
  `reconciliation_user_name` VARCHAR(100) DEFAULT NULL,
  `reconciliation_diff_desc` VARCHAR(500) DEFAULT NULL,
  `attachment_url` VARCHAR(500) DEFAULT NULL,
  `attachment_name` VARCHAR(255) DEFAULT NULL,
  `attachment_size` BIGINT DEFAULT NULL,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_t_bill_no` (`bill_no`),
  KEY `idx_t_bill_enterprise_id` (`enterprise_id`),
  CONSTRAINT `fk_t_bill_enterprise` FOREIGN KEY (`enterprise_id`) REFERENCES `enterprise` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='账单表';

CREATE TABLE IF NOT EXISTS `t_invoice` (
  `id` VARCHAR(36) NOT NULL,
  `invoice_no` VARCHAR(64) NOT NULL,
  `enterprise_id` VARCHAR(36) NOT NULL,
  `invoice_type` INT NOT NULL,
  `invoice_title` VARCHAR(200) NOT NULL,
  `taxpayer_id` VARCHAR(50) DEFAULT NULL,
  `address` VARCHAR(500) DEFAULT NULL,
  `phone` VARCHAR(30) DEFAULT NULL,
  `bank_name` VARCHAR(100) DEFAULT NULL,
  `bank_account` VARCHAR(100) DEFAULT NULL,
  `invoice_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `tax_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `total_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `currency` VARCHAR(10) NOT NULL DEFAULT 'CNY',
  `invoice_content` VARCHAR(500) DEFAULT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `application_time` DATETIME DEFAULT NULL,
  `audit_time` DATETIME DEFAULT NULL,
  `invoice_time` DATETIME DEFAULT NULL,
  `invoice_code` VARCHAR(50) DEFAULT NULL,
  `invoice_number` VARCHAR(50) DEFAULT NULL,
  `invoice_date` DATE DEFAULT NULL,
  `issuer` VARCHAR(100) DEFAULT NULL,
  `payee` VARCHAR(100) DEFAULT NULL,
  `reviewer` VARCHAR(100) DEFAULT NULL,
  `audit_opinion` VARCHAR(500) DEFAULT NULL,
  `auditor_user_id` VARCHAR(36) DEFAULT NULL,
  `auditor_user_name` VARCHAR(100) DEFAULT NULL,
  `cancel_reason` VARCHAR(500) DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `canceller_user_id` VARCHAR(36) DEFAULT NULL,
  `canceller_user_name` VARCHAR(100) DEFAULT NULL,
  `reissue_invoice_id` VARCHAR(36) DEFAULT NULL,
  `original_invoice_id` VARCHAR(36) DEFAULT NULL,
  `invoice_file_url` VARCHAR(500) DEFAULT NULL,
  `invoice_file_name` VARCHAR(255) DEFAULT NULL,
  `invoice_file_size` BIGINT DEFAULT NULL,
  `related_business_type` VARCHAR(32) DEFAULT NULL,
  `related_business_id` VARCHAR(36) DEFAULT NULL,
  `related_business_desc` VARCHAR(255) DEFAULT NULL,
  `remark` VARCHAR(500) DEFAULT NULL,
  `is_red_invoice` TINYINT(1) NOT NULL DEFAULT 0,
  `red_invoice_reason` VARCHAR(500) DEFAULT NULL,
  `red_invoice_no` VARCHAR(64) DEFAULT NULL,
  `delivery_method` VARCHAR(32) DEFAULT NULL,
  `recipient_name` VARCHAR(100) DEFAULT NULL,
  `recipient_phone` VARCHAR(30) DEFAULT NULL,
  `recipient_address` VARCHAR(500) DEFAULT NULL,
  `tracking_no` VARCHAR(100) DEFAULT NULL,
  `delivery_time` DATETIME DEFAULT NULL,
  `receive_time` DATETIME DEFAULT NULL,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_t_invoice_no` (`invoice_no`),
  KEY `idx_t_invoice_enterprise_id` (`enterprise_id`),
  CONSTRAINT `fk_t_invoice_enterprise` FOREIGN KEY (`enterprise_id`) REFERENCES `enterprise` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='发票表';

CREATE TABLE IF NOT EXISTS `notifications` (
  `id` VARCHAR(36) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `content` TEXT NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'UNREAD',
  `user_id` VARCHAR(36) DEFAULT NULL,
  `enterprise_id` VARCHAR(36) NOT NULL,
  `sender_id` VARCHAR(36) DEFAULT NULL,
  `related_id` VARCHAR(36) DEFAULT NULL,
  `related_type` VARCHAR(50) DEFAULT NULL,
  `priority` VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
  `expires_at` DATETIME DEFAULT NULL,
  `read_at` DATETIME DEFAULT NULL,
  `extra_data` TEXT,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_notifications_enterprise_id` (`enterprise_id`),
  KEY `idx_notifications_user_id` (`user_id`),
  KEY `idx_notifications_status` (`status`),
  CONSTRAINT `fk_notifications_enterprise` FOREIGN KEY (`enterprise_id`) REFERENCES `enterprise` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_notifications_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通知表';

CREATE TABLE IF NOT EXISTS `enterprise_files` (
  `id` VARCHAR(36) NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `original_name` VARCHAR(255) DEFAULT NULL,
  `file_type` VARCHAR(50) NOT NULL,
  `file_size` BIGINT DEFAULT NULL,
  `mime_type` VARCHAR(100) DEFAULT NULL,
  `file_path` VARCHAR(500) DEFAULT NULL,
  `file_url` VARCHAR(500) DEFAULT NULL,
  `md5` VARCHAR(64) DEFAULT NULL,
  `enterprise_id` VARCHAR(36) NOT NULL,
  `upload_user_id` VARCHAR(36) DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  `description` VARCHAR(500) DEFAULT NULL,
  `review_status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  `review_remark` VARCHAR(500) DEFAULT NULL,
  `review_by` VARCHAR(36) DEFAULT NULL,
  `review_at` VARCHAR(50) DEFAULT NULL,
  `download_count` INT NOT NULL DEFAULT 0,
  `metadata` TEXT,
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_enterprise_files_enterprise_id` (`enterprise_id`),
  CONSTRAINT `fk_enterprise_files_enterprise` FOREIGN KEY (`enterprise_id`) REFERENCES `enterprise` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='企业文件表';

CREATE TABLE IF NOT EXISTS `data_dict` (
  `id` VARCHAR(36) NOT NULL,
  `dict_type` VARCHAR(50) NOT NULL,
  `dict_code` VARCHAR(50) NOT NULL,
  `dict_name` VARCHAR(100) NOT NULL,
  `parent_id` VARCHAR(36) DEFAULT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` ENUM('ACTIVE', 'DISABLED') NOT NULL DEFAULT 'ACTIVE',
  `created_by` VARCHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(36) DEFAULT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 0,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_data_dict_type_code` (`dict_type`, `dict_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据字典表';

INSERT IGNORE INTO `data_dict` (`id`, `dict_type`, `dict_code`, `dict_name`, `sort_order`, `status`) VALUES
(UUID(), 'TRADE_DIRECTION', 'IMPORT', '进口', 1, 'ACTIVE'),
(UUID(), 'TRADE_DIRECTION', 'EXPORT', '出口', 2, 'ACTIVE'),
(UUID(), 'TRADE_DIRECTION', 'DOMESTIC', '国内', 3, 'ACTIVE'),
(UUID(), 'TRANSPORT_TYPE', 'SEA', '海运', 1, 'ACTIVE'),
(UUID(), 'TRANSPORT_TYPE', 'AIR', '空运', 2, 'ACTIVE'),
(UUID(), 'TRANSPORT_TYPE', 'RAIL', '铁路', 3, 'ACTIVE'),
(UUID(), 'TRANSPORT_TYPE', 'ROAD', '公路', 4, 'ACTIVE'),
(UUID(), 'TRANSPORT_TYPE', 'MULTIMODAL', '多式联运', 5, 'ACTIVE'),
(UUID(), 'INSURANCE_PRODUCT', 'CARGO', '货运险', 1, 'ACTIVE'),
(UUID(), 'INSURANCE_PRODUCT', 'LIABILITY', '责任险', 2, 'ACTIVE'),
(UUID(), 'USER_ROLE', 'SUPER_ADMIN', '超级管理员', 1, 'ACTIVE'),
(UUID(), 'USER_ROLE', 'ADMIN', '管理员', 2, 'ACTIVE'),
(UUID(), 'USER_ROLE', 'OPERATOR', '操作员', 3, 'ACTIVE'),
(UUID(), 'USER_ROLE', 'FINANCE', '财务员', 4, 'ACTIVE');

INSERT IGNORE INTO `enterprise` (
  `id`, `name`, `credit_code`, `contact_name`, `contact_phone`, `contact_email`, `address`, `description`, `status`, `balance`, `frozen_balance`, `total_recharged`, `total_consumed`
) VALUES (
  '00000000-0000-0000-0000-000000000001',
  '安佐科技（开发）',
  '91310000100000000X',
  '管理员',
  '13800000001',
  'admin@anzo.com',
  '上海市浦东新区演示地址 1 号',
  '开发环境默认企业',
  'ACTIVE',
  1000000.00,
  0.00,
  1000000.00,
  0.00
);

INSERT IGNORE INTO `user` (
  `id`, `enterprise_id`, `username`, `password_hash`, `real_name`, `phone`, `email`, `role`, `status`
) VALUES (
  '00000000-0000-0000-0000-000000000002',
  '00000000-0000-0000-0000-000000000001',
  'admin@anzo.com',
  '$2a$10$g.s5lcV1YiST9lKGf2V8R.TLKNc84ETqDz/nBfS2fm0oJ09JrRf6O',
  '系统管理员',
  '13800000001',
  'admin@anzo.com',
  'SUPER_ADMIN',
  'ACTIVE'
);

INSERT IGNORE INTO `customer` (`id`, `enterprise_id`, `name`, `credit_code`, `contact_name`, `contact_phone`, `status`) VALUES
('10000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001', 'ABC进出口有限公司', '91310000100000001X', '张经理', '13800138001', 'ACTIVE'),
('10000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'XYZ科技有限公司', '91310000100000002X', '李总监', '13800138002', 'ACTIVE'),
('10000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000001', '北京物流有限公司', '91310000100000003X', '王主管', '13800138003', 'ACTIVE');

INSERT IGNORE INTO `insurance_insurer` (
  `id`, `insurer_no`, `insurer_name`, `insurer_name_en`, `status`, `remark`
) VALUES
('insurer-1', 'PICC', '中国人民财产保险', 'PICC Property and Casualty', 'ACTIVE', '默认保司数据'),
('insurer-2', 'CPIC', '中国太平洋财产保险', 'CPIC Property Insurance', 'ACTIVE', '默认保司数据'),
('insurer-3', 'PINGAN', '中国平安财产保险', 'Ping An Property Insurance', 'ACTIVE', '默认保司数据');

INSERT IGNORE INTO `t_wallet` (
  `id`, `enterprise_id`, `available_balance`, `frozen_balance`, `total_recharge_amount`, `total_consumption_amount`, `total_refund_amount`, `currency`, `min_balance_alert`, `balance_alert_enabled`, `status`
) VALUES (
  '20000000-0000-0000-0000-000000000001',
  '00000000-0000-0000-0000-000000000001',
  1000000.00,
  0.00,
  1000000.00,
  0.00,
  0.00,
  'CNY',
  1000.00,
  1,
  0
);

SET FOREIGN_KEY_CHECKS = 1;
